# Generated by Django 3.1.5 on 2021-06-04 20:23

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Pic',
            field=models.ImageField(default='/general/titlelogo.png', upload_to=account.models.get_uplaod_file_name),
        ),
    ]
