# Generated by Django 3.2 on 2021-06-21 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='images/vegan.jpeg', null=True, upload_to='images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pros', models.TextField(blank=True, null=True)),
                ('comments', models.JSONField(blank=True, default=list, null=True)),
                ('debate_pros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='debate.debate')),
                ('like', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cons', models.TextField(blank=True, null=True)),
                ('comments', models.JSONField(blank=True, default=dict, null=True)),
                ('debate_cons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons', to='debate.debate')),
            ],
        ),
    ]
