# Generated by Django 3.2 on 2021-06-22 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pros',
            old_name='like',
            new_name='proslike',
        ),
        migrations.AddField(
            model_name='cons',
            name='cons_tags',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cons',
            name='conslike',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debate',
            name='pros_tags',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pros',
            name='pros_tags',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
