# Generated by Django 3.1 on 2021-06-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='comments',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
