# Generated by Django 3.2 on 2021-06-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_auto_20210622_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cons',
            name='cons_tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='debate',
            name='pros_tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pros',
            name='pros_tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
