# Generated by Django 3.2 on 2021-06-15 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_debate_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='pros',
        ),
        migrations.CreateModel(
            name='Pros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pros', models.TextField(blank=True, null=True)),
                ('comments', models.JSONField(blank=True, default=dict, null=True)),
                ('debate_pros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='debate.debate')),
            ],
        ),
        migrations.CreateModel(
            name='Cons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cons', models.TextField(blank=True, null=True)),
                ('comments', models.JSONField(blank=True, default=dict, null=True)),
                ('debate_cons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cons', to='debate.debate')),
            ],
        ),
    ]
