# Generated by Django 3.2 on 2021-06-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_auto_20210615_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='comments',
        ),
    ]
