# Generated by Django 3.2 on 2021-06-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_auto_20210622_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debate',
            old_name='pros_tags',
            new_name='tags',
        ),
    ]
