# Generated by Django 3.2 on 2021-06-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_remove_debate_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images'),
        ),
    ]
