# Generated by Django 3.2 on 2021-06-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0005_debate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pros',
            name='comments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
