# Generated by Django 3.2 on 2021-06-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0005_alter_cons_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cons',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='pros',
            old_name='comments',
            new_name='comment',
        ),
    ]
