# Generated by Django 3.2 on 2021-06-23 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debate', '0006_auto_20210623_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='proslike',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
