# Generated by Django 3.2 on 2021-06-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0006_alter_pros_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='slug',
            field=models.SlugField(default='slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
