# Generated by Django 3.2 on 2021-08-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0008_auto_20210624_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
