# Generated by Django 3.1 on 2021-06-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1300)),
                ('media_type', models.CharField(blank=True, max_length=10, null=True)),
                ('media_quantity', models.IntegerField(default=0)),
                ('media', models.JSONField(blank=True, default=dict, null=True)),
                ('likes', models.JSONField(blank=True, default=dict, null=True)),
                ('comments', models.JSONField(blank=True, default=dict, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_edited', models.BooleanField(default=False)),
            ],
        ),
    ]
